# Generated by Django 4.2.5 on 2024-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=70)),
                ('classhour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classdate', models.DateField()),
            ],
        ),
    ]
